<a href="https://colab.research.google.com/github/Shrey-tspmo/DAV_4NI25CS183_github/blob/main/DAV_lab_session_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("Numpy version:",np.__version__)              # to upgrade , pip install --upgrade

Numpy version: 2.0.2


In [ ]:
marks = np.array([78,85,92,67,88])
print("Marks:",marks)
print("Type:",type(marks))

Marks: [78 85 92 67 88]
Type: <class 'numpy.ndarray'>


In [ ]:
print("Number of dimensions:",marks.ndim)
print("Shape:",marks.shape)
print("Number of elements:",marks.size)

Number of dimensions: 1
Shape: (5,)
Number of elements: 5


In [ ]:
  marks = np.array([78,85,92,67,88])
  print("Original",marks)
  print("Add 5:",marks+5)
  print("Subtract 2:",marks-2)
  print("Multiply 2:",marks*2)
  print("Divide 2:",marks/2)
  print("Square:",marks**2)

Original [78 85 92 67 88]
Add 5: [83 90 97 72 93]
Subtract 2: [76 83 90 65 86]
Multiply 2: [156 170 184 134 176]
Divide 2: [39.  42.5 46.  33.5 44. ]
Square: [6084 7225 8464 4489 7744]


In [ ]:
print("Sum:",marks.sum())
print("Mean:",marks.mean())
print("Max:",marks.max())
print("Min:",marks.min())

Sum: 410
Mean: 82.0
Max: 92
Min: 67


In [ ]:
print("First mark:",marks[0])
print("Second mark:",marks[1])
print("Last mark:",marks[-1])

First mark: 78
Second mark: 85
Last mark: 88


In [ ]:
print("Index 1 to 3:",marks[1:4])
print("First three:",marks[:3])
print("From idex 2:",marks[2:])
print("Every second:",marks[::2])

Index 1 to 3: [85 92 67]
First three: [78 85 92]
From idex 2: [92 67 88]
Every second: [78 92 88]


In [ ]:
student_marks = np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89]                                                                           #imp
])
print(student_marks)
print("Shape:",student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)


In [ ]:
print("Mean of all values:",student_marks.mean())
print("Column-wise mean:",student_marks.mean(axis=0))    # mean of each column          #imp
print("Row-wise mean:",student_marks.mean(axis=1))       # mean of each row

Mean of all values: 84.44444444444444
Column-wise mean: [78.33333333 89.33333333 85.66666667]
Row-wise mean: [85.         77.         91.33333333]


In [ ]:
import pandas as pd
print("Pandas version:",pd.__version__)

Pandas version: 2.2.3


In [ ]:
data = {
    "Name":["Anu","Rahul","Kiran","Priya"],
    "Branch":["CSE","AIML","CSE","AIML"],
    "Marks":[85,91,76,88]
}
df = pd.DataFrame(data)
df    # u can also use print(df) but then u wont get the nice outlines that make it look like excel

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
print("Shape:",df.shape)
print("\nColumns:")
print(df.columns)

Shape: (4, 3)

Columns:
Index(['Name', 'Branch', 'Marks'], dtype='object')


In [ ]:
df.head()

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
df.describe()

,Marks
count,4.000000
mean,85.000000
std,6.480741
min,76.000000
25%,82.750000
50%,86.500000
75%,88.750000
max,91.000000


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [ ]:
df.tail()

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
print("Marks:")
print(df["Marks"])
print("\nName:")                                                      # imp
print(df["Name"])
print("\nBranch and Marks:")
print(df[["Branch","Marks"]])


Marks:
0    85
1    91
2    76
3    88
Name: Marks, dtype: int64

Name:
0      Anu
1    Rahul
2    Kiran
3    Priya
Name: Name, dtype: object

Branch and Marks:
  Branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88


In [ ]:
print("Frist Row:")
print(df.iloc[0])              # interger location based indexing = iloc i.e integer location
print("\nSecond Row:")
print(df.iloc[1])
print("\nLast Row:")
print(df.iloc[-1])
print("\nFirst 2 rows:")
print(df.iloc[:2])

Frist Row:
Name      Anu
Branch    CSE
Marks      85
Name: 0, dtype: object

Second Row:
Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

Last Row:
Name      Priya
Branch     AIML
Marks        88
Name: 3, dtype: object

First 2 rows:
    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91


In [ ]:
print("Rows 1 to 3 , Names and marks:")
display(df.iloc[1:4,0:3])

Rows 1 to 3 , Names and marks:


,Name,Branch,Marks
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
print("Frist two rows and first two columns")
print(df.iloc[0:2,0:2])

Frist two rows and first two columns
    Name Branch
0    Anu    CSE
1  Rahul   AIML


In [ ]:
high_score = df[df["Marks"] > 90]
high_score            # here , again u can do print(high_score) but u wont get the pretty excel effect

,Name,Branch,Marks
1,Rahul,AIML,91


In [ ]:
print("Students from CSE:")
display(df[df["Branch"] == "CSE"])

print("Students who have scored above OR equle to  85:")
display(df[df["Marks"] >= 85])

Students from CSE:


,Name,Branch,Marks
0,Anu,CSE,85
2,Kiran,CSE,76


Students who have scored above OR equle to  85:


,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
3,Priya,AIML,88


In [ ]:
# Question
data = {
    "Name": ["Asha","Bharat","Chetan","Divya","Esha"],
    "Department": ["CSE","ISE","CSE","AIML","ISE"],
    "Marks":[72,91,84,95,68],
    "Attendance": [82,94,88,96,75]
}
students = pd.DataFrame(data)
students

,Name,Department,Marks,Attendance
0,Asha,CSE,72,82
1,Bharat,ISE,91,94
2,Chetan,CSE,84,88
3,Divya,AIML,95,96
4,Esha,ISE,68,75


In [ ]:
#ANSS

print("\nName and Marks:")
print(students[["Name","Marks"]])

print("Students who have scored higher than 80")
higher_score = students[students["Marks"] > 80]
higher_score

print("Studnets whose attendence is higher than 85")
higher_att = students[students["Attendance"] > 80]
higher_att

print("First three students:")
display(students.iloc[:3])

print("Average marks:")
print(students["Marks"].mean())

print("Max marks:")
display(students[students["Marks"] == students["Marks"].max()])

print("Studnets from CSE department:")
display(students[students["Department"] == "CSE"])

print("Studnets who have scored above 80 and attendence is above 85%")
display(students[(students["Marks"] > 80) & (students["Attendance"] > 85)])


Name and Marks:
     Name  Marks
0    Asha     72
1  Bharat     91
2  Chetan     84
3   Divya     95
4    Esha     68
Students who have scored higher than 80
Studnets whose attendence is higher than 85
First three students:


,Name,Department,Marks,Attendance
0,Asha,CSE,72,82
1,Bharat,ISE,91,94
2,Chetan,CSE,84,88


Average marks:
82.0
Max marks:


,Name,Department,Marks,Attendance
3,Divya,AIML,95,96


Studnets from CSE department:


,Name,Department,Marks,Attendance
0,Asha,CSE,72,82
2,Chetan,CSE,84,88


Studnets who have scored above 80 and attendence is above 85%


,Name,Department,Marks,Attendance
1,Bharat,ISE,91,94
2,Chetan,CSE,84,88
3,Divya,AIML,95,96
